const plants = [
    {
        "name": "Swiss Cheese Plant",
        "description": "The Swiss Cheese Plant was a 70's cult classic, its retro-chic appeal makes it just as popular today and rightly so. Its large, glossy, heart shaped, leaves add fantastic impact with their perforations and lobes, which develop as the leaf matures.",
        "price": "$10.00",
        "size": "medium",
        "type": "perennial",
        "images": "swisscheese.jpg",
        "care": "Medium Care",
        "light": "Bright light",
        "room" : "office",
        "sadSigns": "Leaves turning brown and crispy at the edges - Wilting plant, dry potting mix - Yellowing leaves or black stems",
        "lightRatio": "0.6",
        "waterRatio": "0.5",
        "careRatio": "0.7"
    },
    {
        "name": "Dracaena Compacta",
        "description": "Compacta as the name suggests is a compact version of Dracaena fragrans. The hydroculture multi-stem version provides height and helps display the tropical lush deep green foliage at different levels on separate stems. Dracaena Compacta likes bright conditions and enjoys slightly raised humidity. Like all Dracaena it helps purify the surrounding air.",
        "price": "$12.00",
        "size": "small",
        "type": "tropical perennial",
        "images": "dracaenacompacta.jpg",
        "care": "High Care",
        "light": "Bright light",
        "room" : "bathroom",
        "sadSigns": "Crispy or curling pale leaves - Yellowing leaves, wet potting mix",
        "lightRatio": "0.5",
        "waterRatio": "0.4",
        "careRatio": "0.6"
        
    },
    {
        "name": "Pilea Peperomioides",
        "description": "Pilea peperomioides is an easy to grow modern looking houseplant. Also called the Chinese Money Plant or Pancake Plant, it's straightforward to care for and simple to propagate. Whether you're a newbie to houseplants or a seasoned expert, a Pilea peperomioides plant is sure to be a welcome addition to any indoor plant collection.",
        "price": "$15.00",
        "size": "medium",
        "type": "Tropical perennial",
        "images": "pileapeperomioides.jpg",
        "care": "Low Care",
        "light": "Medium light",
        "room" : "kitchen",
        "sadSigns": "Soft, darkened base - Curled or shriveled leaves - Low humidity, underwatered - Not green when wet",
        "lightRatio": "0.3",
        "waterRatio": "0.6",
        "careRatio": "0.8"
        
    },
    {
        "name": "Neanthe Bella Palm",
        "description": "Also called Chamaedorea elegans and parlor palm, the Neanthe Bella Palm is a small and delicate palm tree. Its bushy green fronds emerge densely from thin green stems. This plant reaches about 3-4 feet in height. It prefers bright light and evenly moist soil. This palm tree is soft and touchable while adding plenty of tropical punch.",
        "price": "$7.00",
        "size": "medium",
        "type": "Tropical perennial",
        "images": "neanthebellapalm.jpg",
        "care": "High Care",
        "light": "Low light",
        "room" : "garden",
        "sadSigns": "Wrinkling leaves - Mushy stems, wet potting mix - Leaf drop ",
        "lightRatio": "0.6",
        "waterRatio": "0.4",
        "careRatio": "0.6"
        
    },
    {
        "name": "Dracaena Lemon Lime",
        "description": "If you enjoy easy care and bright color, the Dracaena Lemon Lime, sometimes called a corn plant, is the plant for you. As the name suggests, the leaves are chartreuse with a thick band of darker green down the centers. This mix of colors is perfect for pepping up your space. Dracaenas, sometimes called dragon plants, range from small and bush-like in their juvenile form to lanky, whimsical trees in their mature form.",
        "price": "$16.00",
        "size": "medium",
        "type": "Tropical perennial",
        "images": "dracaenalemonlime.jpg",
        "care": "Medium Care",
        "light": "Bright light",
        "room" : "kitchen",
        "sadSigns": "Yellowing leaves, New flowers are green instead of red or pink, Flowers are turning pale green, Leaf elongation. ",
        "lightRatio": "0.5",
        "waterRatio": "0.2",
        "careRatio": "0.9"
        
    },
    {
        "name": "Snake Plant Laurentii",
        "description": "The Snake Plant Laurentii, or Sansevieria trifasciata 'Laurentii', is a succulent plant characterized by its upright sword-like leaves with vibrant yellow edges. It is popular for its incredibly easy-going nature (it can tolerate low light and drought) and its air-purifying capabilities. The easiest way to kill this plant is to overcare for it. ",
        "price": "$44.00",
        "size": "medium",
        "type": "Tropical perennial",
        "images": "snakeplant.jpg",
        "care": "Low Care",
        "light": "Medium light",
        "room" : "bathroom",
        "sadSigns": "Yellowing leaves, New flowers are green instead of red or pink, Flowers are turning pale green, Leaf elongation. ",
        "lightRatio": "0.1",
        "waterRatio": "0.2",
        "careRatio": "0.3"
        
    },
    {
        "name": "ZZ Plant",
        "description": "The ZZ Plant is characterized by its waxy green leaves above the surface of its potting mix, and its large potato-like rhizomes underneath. These rhizomes store water, making the ZZ a hardy, drought-tolerant houseplant that only needs water every few weeks.",
        "price": "$58.00",
        "size": "medium",
        "type": "Tropical perennial",
        "images": "zzplant.jpg",
        "care": "High Care",
        "light": "Low light",
        "room" : "bathroom",
        "sadSigns": "Wrinkling leaves - Mushy stems, wet potting mix - Leaf drop ",
        "lightRatio": "0.7",
        "waterRatio": "0.6",
        "careRatio": "0.8"
        
    },
    {
        "name": "Money Tree Plant",
        "description": "Said to bring good luck and fortune, the Money Tree is the perfect plant to add to any room of your home to create good Feng Shui. It is known for its resilience, ease of growth, and fun braided trunk. ",
        "price": "$58.00",
        "size": "small",
        "type": "Tree",
        "images": "moneytreeplant.jpg",
        "care": "Medium Care",
        "light": "Bright light",
        "room" : "office",
        "sadSigns": "Yellowing leaves, New flowers are green instead of red or pink, Flowers are turning pale green, Leaf elongation. ",
        "lightRatio": "0.8",
        "waterRatio": "0.7",
        "careRatio": "0.9"
        
    },
    {
        "name": "Bromeliad Antonio Pink",
        "description": "The “pink” in Bromeliad Antonio Pink describes the fuchsia bracts found in this cultivar, which sometimes produce short-blooming purple flowers. Its vibrant bract also gives it its nickname, the Pink Quill Plant. This plant is pet-friendly!",
        "price": "$64.00",
        "size": "small",
        "type": "Bromeliad",
        "images": "bromeliadantonio.jpg",
        "care": "Low Care",
        "light": "Low light",
        "room" : "garden",
        "sadSigns": "Yellowing leaves, New flowers are green instead of red or pink, Flowers are turning pale green, Leaf elongation. ",
        "lightRatio": "0.9",
        "waterRatio": "0.7",
        "careRatio": "0.6"
        
    },
    {
        "name": "Dracaena Marginata",
        "description": "The Dracaena marginata, or Dragon Tree, is a popular low-maintenance plant native to Madagascar. Its unique silhouette and height make it our go-to pick for upgrading any corner!",
        "price": "$60.00",
        "size": "medium",
        "type": "Broadleaf evergreen",
        "images": "dracaenamarginata.jpg",
        "care": "Low Care",
        "light": "Medium light",
        "room" : "living room",
        "sadSigns": "Wrinkling leaves - Mushy stems, wet potting mix - Leaf drop ",
        "lightRatio": "0.8",
        "waterRatio": "0.9",
        "careRatio": "0.2"
        
    },
    {
        "name": "White Orchid",
        "description": "With its elegant stems and vibrant white flowers, this Phalaenopsis orchid makes any space feel chicer. You may notice a small number of blooms on your orchid upon delivery. These blooms will open quicker in a warm indoor setting. The Phalaenopsis will typically bloom about once a year for up to three months. After a blooming cycle, the flowers will wilt and fall off. This is the orchid’s way to store up energy to re-bloom again next season. ",
        "price": "$98.00",
        "size": "small",
        "type": "Tropical perennial",
        "images": "whiteorchid.jpg",
        "care": "High Care",
        "light": "Low light",
        "room" : "living room",
        "sadSigns": "Yellowing leaves, New flowers are green instead of red or pink, Flowers are turning pale green, Leaf elongation. ",
        "lightRatio": "0.1",
        "waterRatio": "0.4",
        "careRatio": "0.2"
        
    },
    {
        "name": "Large Fan Palm",
        "description": "The Fan Palm, Livistona chinensis, is a statement-making plant that takes very little effort to care for; it will be happy in a variety of indoor and outdoor spaces. It is partial to less frequent waterings and bright light, as these will help it retain its foliage. Sized to ship best, our large Fan Palm arrives with room to grow as it adapts to your home’s conditions. This plant is pet-friendly!",
        "price": "$88.00",
        "size": "large",
        "type": "Tropical perennial",
        "images": "largefanpalm.jpg",
        "care": "Low Care",
        "light": "Bright light",
        "room" : "garden",
        "sadSigns": "Soft, darkened base - Curled or shriveled leaves - Low humidity, underwatered - Not green when wet",
        "lightRatio": "0.9",
        "waterRatio": "0.8",
        "careRatio": "0.3"
        
    },
    {
        "name": "Large Ficus Audrey",
        "description": "The Ficus Audrey has matte green leaves and thick, white stems. It thrives in filtered bright light with waterings every 1–2 weeks. Audrey’s easy-going nature and low-maintenance care routine make it a popular variety of ficus to grow as a houseplant. Sized to ship best, our large Ficus Audrey arrives with room to grow as it adapts to your home’s conditions.",
        "price": "$108.00",
        "size": "large",
        "type": "Tropical perennial",
        "images": "largeficusaudrey.jpg",
        "care": " Medium Care",
        "light": "Medium light",
        "room" : "kitchen",
        "sadSigns": "Soft, darkened base - Curled or shriveled leaves - Low humidity, underwatered - Not green when wet",
        "lightRatio": "0.7",
        "waterRatio": "0.4",
        "careRatio": "0.2"
        
    },
    {
        "name": "Large Fiddle Leaf Fig Tree",
        "description": "The Fiddle Leaf Fig, or Ficus lyrata, is famous for its broad green leaves with prominent veining. It is sometimes described as “fickle” but will thrive in an environment with stable temps and bright light. Sized to ship best, our large Fiddle Leaf Fig arrives with room to grow as it adapts to your home’s conditions.",
        "price": "$118.00",
        "size": "large",
        "type": "Tropical perennial",
        "images": "largefiddleleaf.jpg",
        "care": "Low Care",
        "light": "Bright light",
        "room" : "bathroom",
        "sadSigns": "Yellowing leaves, New flowers are green instead of red or pink, Flowers are turning pale green, Leaf elongation. ",
        "lightRatio": "0.6",
        "waterRatio": "0.9",
        "careRatio": "0.8"
        
    },
    {
        "name": "Blue Orchid ",
        "description": "Watercolor orchids are Phalaenopsis orchids dyed using a safe and natural method. You may notice a small number of blooms on your orchid upon delivery. These blooms will open quicker in a warm indoor setting. Phalaenopsis orchids typically bloom about once a year for up to three months. After a blooming cycle, the flowers will wilt and fall off. This is the orchid’s way to store up energy to re-bloom again next season. When they re-bloom, their flowers will be their natural color.  ",
        "price": "$80.00",
        "size": " medium",
        "type": "Orchid ",
        "images": "blue-orchid.jpg",
        "care": "High Care",
        "light": "Low light",
        "room" : "garden",
        "sadSigns": "Wrinkling leaves - Mushy stems, wet potting mix - Leaf drop ",
        "lightRatio": "0.2",
        "waterRatio": "0.3",
        "careRatio": "0.8"
        
    },
    {
        "name": "Ric Rac Cactus",
        "description": "The Ric Rac Cactus is known for its fishbone-shaped trailing stems and the occasional night-blooming flower, while the Arrowhead White Butterfly’s dart-shaped leaves showcase a unique white and green variegation. ",
        "price": "$50.00",
        "size": "small",
        "type": "Broadleaf evergreen",
        "images": "ric-rac.jpg",
        "care": "Low Care",
        "light": " Medium light",
        "room" : "bedroom",
        "sadSigns": "Soft, darkened base - Curled or shriveled leaves - Low humidity, underwatered - Not green when wet",
        "lightRatio": "0.2",
        "waterRatio": "0.6",
        "careRatio": "0.5"
        
    },
    {
        "name": "Coffee Plant",
        "description": "You might be surprised to know the same plant that grows your morning coffee beans is a popular, low-maintenance houseplant! Although it’s unlikely this plant will produce berries inside, its attractive shiny green foliage will liven up any interior space. ",
        "price": "$46.00",
        "size": "small",
        "type": "Broadleaf evergreen",
        "images": "coffee-plant.jpg",
        "care": "Low Care",
        "light": "Medium light",
        "room" : "bathroom",
        "sadSigns": "Yellowing leaves, New flowers are green instead of red or pink, Flowers are turning pale green, Leaf elongation. ",
        "lightRatio": "0.9",
        "waterRatio": "0.2",
        "careRatio": "0.3"
        
    },
    {
        "name": "Echeveria Lola",
        "description": "The Echeveria is our equivalent of the rose. This iconic succulent has fleshy drought-tolerant green leaves that grow in a chic rosette shape. It’s the perfect pick-me-up plant for yourself or a friend. ",
        "price": "$32",
        "size": "mini",
        "type": "succulent",
        "images": "echeveria-lola.jpg",
        "care": "Medium Care",
        "light": "Medium light",
        "room" : "kitchen",
        "sadSigns": "Soft, darkened base - Curled or shriveled leaves - Low humidity, underwatered - Not green when wet",
        "lightRatio": "0.9",
        "waterRatio": "0.2",
        "careRatio": "0.8"
        
    },
    {
        "name": "Fiddle Leaf Fig",
        "description": "The Fiddle Leaf Fig, or Ficus lyrata, is famous for its broad green leaves with prominent veining. It is sometimes described as “fickle” but will thrive in an environment with stable temps and bright light. Sized to ship best, our large Fiddle Leaf Fig arrives with room to grow as it adapts to your home’s conditions.",
        "price": "$118.00",
        "size": "big",
        "type": "tree",
        "images": "fiddle-leaf.jpg",
        "care": "Medium Care",
        "light": "Bright light",
        "room" : "living room",
        "sadSigns": "Yellowing leaves, New flowers are green instead of red or pink, Flowers are turning pale green, Leaf elongation. ",
        "lightRatio": "0.2",
        "waterRatio": "0.8",
        "careRatio": "0.1"
        
    },
    {
        "name": "Hoya Heart",
        "description": "The Hoya kerrii is commonly called the Hoya Heart because of its green heart-shaped leaves. This single leaf cutting is a fun, whimsical way to show your plant love. It is partially rooted but does not have a node. It will stay as an adorable heart-shaped leaf for years to come.",
        "price": "$18",
        "size": "mini",
        "type": "succulent",
        "images": "hoya-heart.jpg",
        "care": "Medium Care",
        "light": "Bright light",
        "room" : "bedroom",
        "sadSigns": "Wrinkling leaves - Mushy stems, wet potting mix - Leaf drop ",
        "lightRatio": "0.7",
        "waterRatio": "0.5",
        "careRatio": "0.2"
        
    },
    {
        "name": "Red Anthurium",
        "description": "Also known as the flamingo flower, the Anthurium is the world’s longest blooming houseplant. It is rarely without its showy blooms. These aren’t actual flowers, but modified waxy leaves that circle the pointed spadix, home to the plant's real, and very tiny, flowers. Each can last up to eight weeks—bringing a fun pop of color to your space year-round. ",
        "price": "$118.00",
        "size": "small",
        "type": "perennial",
        "images": "red-anthurium.jpg",
        "care": "Medium Care",
        "light": "Medium light",
        "room" : "living room",
        "sadSigns": "Yellowing leaves, New flowers are green instead of red or pink, Flowers are turning pale green, Leaf elongation.",
        "lightRatio": "0.5",
        "waterRatio": "0.2",
        "careRatio": "0.9"
        
    },
    {
        "name": "Schefflera Arboricola",
        "description": "The Schefflera Arboricola features a single or braided trunk and tree-like clusters of leaflets, which have been likened to umbrellas, wheels, and octopi! You can help it retain its foliage by placing it in bright light and spacing out waterings. Sized to ship best, our large Umbrella Tree arrives with room to grow as it adapts to your home’s conditions.",
        "price": "$118.00",
        "size": "large",
        "type": "tree",
        "images": "schefflera-arboricola.jpg",
        "care": "Low Care",
        "light": "Medium light",
        "room" : "garden",
        "sadSigns": "Soft, darkened base - Curled or shriveled leaves - Low humidity, underwatered - Not green when wet",
        "lightRatio": "0.8",
        "waterRatio": "0.7",
        "careRatio": "0.3"
        
    },
    {
        "name": "String of Hearts",
        "description": "Our String of Hearts is a lovely trailing succulent known for its heart-shaped leaves and tolerant nature. It can propagate quickly due to its shallow roots and ability to easily grow new roots and vines. We recommend putting it on an elevated surface like a bookshelf to give it space to cascade.",
        "price": "$48.00",
        "size": "small",
        "type": "succulent",
        "images": "string-hearts.jpg",
        "care": "Medium Care",
        "light": "Medium light",
        "room" : "bedroom",
        "sadSigns": "Wrinkling leaves - Mushy stems, wet potting mix - Leaf drop ",
        "lightRatio": "0.1",
        "waterRatio": "0.9",
        "careRatio": "0.5"
        
    },
    {
        "name": "Xerographica Air Plant",
        "description": "Air Plants grow without being rooted in soil. This Xerographica is characterized by its silvery grey leaves that form a rosette shape. It measures approximately 5-6' in diameter. They require bright, indirect light and water weekly. All air plants are pet-friendly.",
        "price": "$118.00",
        "size": "small",
        "type": "Air plant ",
        "images": "xerographica-airplant.jpg",
        "care": "Medium Care",
        "light": "Low light",
        "room" : "kitchen",
        "sadSigns": "Soft, darkened base - Curled or shriveled leaves - Low humidity, underwatered - Not green when wet",
        "lightRatio": "0.8",
        "waterRatio": "0.7",
        "careRatio": "0.3"
        
    },
    {
        "name": "Kokedama",
        "description": "A traditional Japanese art form, the word Kokedama translates to ’moss ball’. There is no upkeep necessary with this preserved fern kokedama – simply hang and enjoy, or sit on a flat surface. This is a real kokedama that has been naturally preserved. It is non-toxic and environmentally friendly. Each kokedama is handcrafted and unique – natural variations will occur. There might be a slight odor upon unpacking your kokedama, but it will subside in about 3 weeks. Keep it out of direct light and never water.",
        "price": "$62.00",
        "size": "medium",
        "type": "kokedama",
        "images": "kokedama.jpg",
        "care": "Medium Care",
        "light": "Low light",
        "room" : "bathroom",
        "sadSigns": "Yellowing leaves, New flowers are green instead of red or pink, Flowers are turning pale green, Leaf elongation.",
        "lightRatio": "0.1",
        "waterRatio": "0.9",
        "careRatio": "0.4"
        
    },
    {
        "name": "Faux Tradescantia Zebrina",
        "description": "This Zebrina can’t change its stripes! Our artificial inchplant lends enduring greenery to any space, and it comes in your choice of our medium Grant or Hyde ceramic planter. It is a great indoor plant for those who want a little more space to grow their plants. ",
        "price": "$62.00",
        "size": "medium",
        "type": "perennial",
        "images": "faux-tradescantia",
        "care": "Low Care",
        "light": "Low light",
        "room" : "kitchen",
        "sadSigns": "Soft, darkened base - Curled or shriveled leaves - Low humidity, underwatered - Not green when wet",
        "lightRatio": "0.6",
        "waterRatio": "0.4",
        "careRatio": "0.9"
        
    },
    {
        "name": "Faux Maranta",
        "description": "Marantas can be finicky, but there is no need to fuss with our faux take on the prayer plant. It even comes nestled in a ceramic planter for a look so convincing that eagle-eyed plant parents will mistake your Maranta for the real thing.",
        "price": "$72.00",
        "size": "medium",
        "type": "perennial",
        "images": "faux-maranta.jpg",
        "care": "Low Care",
        "light": "Low light",
        "room" : "kitchen",
        "sadSigns": "Yellowing leaves, New flowers are green instead of red or pink, Flowers are turning pale green, Leaf elongation. ",
        "lightRatio": "0.3",
        "waterRatio": "0.2",
        "careRatio": "0.3"
    
    },
    {
        "name": "Pothos Jade",
        "description": "Pothos plants are loved for their quick-growing, trailing vines that flourish in bright to medium light with weekly waterings. They are an excellent choice for beginner plant parents and require little care. This classic Jade variety is a great way to expand your plant collection while sticking to tried-and-true, easy-care plants.",
        "price": "$44.00",
        "size": "small",
        "type": "perennial",
        "images": "pothos.jpg",
        "care": "Low Care",
        "light": "Medium light",
        "room" : "living room",
        "sadSigns": "Wrinkling leaves - Mushy stems, wet potting mix - Leaf drop ",
        "lightRatio": "0.2",
        "waterRatio": "0.6",
        "careRatio": "0.1"
        
    },
    {
        "name": "Philodendron Brasil",
        "description": "Meet the Philodendron Brasil, a colorful cultivar of our favorite houseplant, the Philodendron hederaceum or heartleaf Philodendron. Its trailing vines feature dark green heart-shaped leaves with strokes of lime green. It is just as easy to care for as the Philodendron Green, but its striking variegation can benefit from brighter light.",
        "price": "$44.00",
        "size": "small",
        "type": "succulent",
        "images": "philodendron-brasil.jpg",
        "care": "Low Care",
        "light": "Medium light",
        "room" : "garden",
        "sadSigns": "Soft, darkened base - Curled or shriveled leaves - Low humidity, underwatered - Not green when wet",
        "lightRatio": "0.1",
        "waterRatio": "0.3",
        "careRatio": "0.4"
        
    },
    
]

export default plants;